
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    firstdb:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.1.2:8108/Detect_4?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: kt4
      password: Detect_4
      driver-class-name: com.mysql.cj.jdbc.Driver
    seconddb:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.1.2:8108/example3?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: kt4
      password: Detect_4
      driver-class-name: com.mysql.cj.jdbc.Driver
    thirddb:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.1.2:8108/qianye?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: kt4
      password: Detect_4
      driver-class-name: com.mysql.cj.jdbc.Driver
    fourthdb:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.1.2:8108/Liuhongrui?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: kt4
      password: Detect_4
      driver-class-name: com.mysql.cj.jdbc.Driver
    fifthdb:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.1.2:8108/HIT?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: kt4
      password: Detect_4
      driver-class-name: com.mysql.cj.jdbc.Driver
    chendb:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.1.2:8108/chenyuepeng?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: kt4
      password: Detect_4
      driver-class-name: com.mysql.cj.jdbc.Driver
    zhengdb:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.1.2:8108/zhengconghui?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: kt4
      password: Detect_4
      driver-class-name: com.mysql.cj.jdbc.Driver
    maxWait: 60000

    timeBetweenEvictionRunsMillis: 60000

    minEvictableIdleTimeMillis: 300000

    validationQuery: SELECT 1

    testWhileIdle: true

    testOnBorrow: true

    testOnReturn: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  freemarker:
    suffix:
      .ftl
  thymeleaf:
    check-template: false
    check-template-location: false
server:
  port: 8383